#!/usr/bin/env bash
# Installing and configuring HAProxy

set -e

apt-get update
apt-get install -y software-properties-common

add-apt-repository -y ppa:vbernat/haproxy-1.8

apt-get update
apt-get install -y haproxy=1.8.*

echo "ENABLED=1" > /etc/default/haproxy

cat <<EOF >> /etc/haproxy/haproxy.cfg
listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server web-01 52.90.22.66:80 check
    server web-02 100.24.238.44:80 check
EOF

systemctl restart haproxy
