#!/usr/bin/env bash
# this script uses while to display "Best School" 10 times

a=1
while ((a<=10)); do
      echo "Best School"
      ((a++))
      if [ "$a" -eq 10 ]
      then
	  echo "Hi"
      fi
done
