#!/usr/bin/env bash
# this script uses while to display "Best School" 10 times

a=1
while ((a<=10)); do
      if [ "$a" -eq 4 ]
      then
	  echo "bad luck"
      elif [ "$a" -eq 8 ]
      then
	  echo "good luck"
      else
	  echo "Best School"
      fi
      ((a++))
done
